/**
 * Vocabulário de busca do Portal Católico.
 *
 * Mais de 400 termos reais de pesquisa em português (Brasil e Portugal),
 * agrupados por área temática. Cada rota monta sua meta `keywords` a partir
 * dos grupos que realmente descrevem a página — nunca a lista inteira, para
 * não diluir o foco semântico de cada URL.
 *
 * Fonte dos termos: intenção de busca observada (pergunta direta, nome de
 * devoção, referência bíblica, dúvida catequética) mantida sempre fiel à
 * doutrina católica.
 */

export const GRUPOS = {
  marca: [
    "portal católico",
    "site católico",
    "portal católico online",
    "biblioteca católica digital",
    "estudo católico online",
    "formação católica online",
    "catequese online",
    "conteúdo católico confiável",
    "igreja católica apostólica romana",
    "fé católica",
    "doutrina católica",
    "tradição da Igreja",
    "magistério da Igreja",
    "o que a Igreja ensina",
    "religião católica",
    "catolicismo",
  ],

  biblia: [
    "Bíblia católica",
    "Bíblia católica online",
    "Bíblia católica completa",
    "Bíblia 73 livros",
    "ler a Bíblia online",
    "Bíblia online grátis",
    "Antigo Testamento",
    "Novo Testamento",
    "livros deuterocanônicos",
    "livros apócrifos católicos",
    "cânon bíblico católico",
    "diferença entre Bíblia católica e protestante",
    "Septuaginta",
    "Vulgata",
    "Pentateuco",
    "Evangelhos",
    "Evangelho de São Mateus",
    "Evangelho de São Marcos",
    "Evangelho de São Lucas",
    "Evangelho de São João",
    "Atos dos Apóstolos",
    "cartas de São Paulo",
    "Apocalipse explicado",
    "Salmos",
    "Salmo 23",
    "Salmo 91",
    "Provérbios",
    "Eclesiástico",
    "Sabedoria",
    "Tobias",
    "Judite",
    "Macabeus",
    "Baruc",
    "Gênesis capítulo 1",
    "Êxodo",
    "Isaías",
    "Jeremias",
    "profetas maiores",
    "profetas menores",
    "versículo do dia",
    "versículos de fé",
    "versículos de esperança",
    "referências cruzadas bíblicas",
    "concordância bíblica",
    "introdução aos livros da Bíblia",
    "contexto histórico da Bíblia",
    "quem escreveu a Bíblia",
    "como ler a Bíblia pela primeira vez",
    "plano de leitura da Bíblia",
    "plano de leitura da Bíblia em um ano",
    "ler a Bíblia em 90 dias",
    "ler os Evangelhos em 30 dias",
    "leitura orante da Palavra",
    "lectio divina",
    "exegese católica",
    "sentido literal e espiritual da Escritura",
  ],

  catecismo: [
    "Catecismo da Igreja Católica",
    "Catecismo online",
    "Catecismo em português",
    "CIC parágrafos",
    "Catecismo 2865 parágrafos",
    "Compêndio do Catecismo",
    "Credo Niceno-Constantinopolitano",
    "Símbolo dos Apóstolos",
    "profissão de fé",
    "dez mandamentos",
    "mandamentos da lei de Deus",
    "mandamentos da Igreja",
    "sete pecados capitais",
    "virtudes cardeais",
    "virtudes teologais",
    "dons do Espírito Santo",
    "frutos do Espírito Santo",
    "obras de misericórdia",
    "pecado mortal e venial",
    "graça santificante",
    "juízo final",
    "novíssimos",
    "céu inferno purgatório",
    "o que é o purgatório",
    "ressurreição da carne",
    "vida eterna",
    "consciência moral",
    "lei natural",
    "doutrina social da Igreja",
    "bem comum",
    "dignidade da pessoa humana",
    "moral católica",
    "bioética católica",
  ],

  sacramentos: [
    "sacramentos da Igreja Católica",
    "sete sacramentos",
    "batismo católico",
    "batismo de crianças",
    "padrinhos de batismo",
    "primeira comunhão",
    "crisma",
    "confirmação sacramento",
    "Eucaristia",
    "o que é a Eucaristia",
    "presença real de Cristo",
    "transubstanciação",
    "comunhão espiritual",
    "adoração ao Santíssimo Sacramento",
    "missa católica explicada",
    "partes da missa",
    "ordinário da missa",
    "confissão católica",
    "como fazer uma boa confissão",
    "exame de consciência",
    "ato de contrição",
    "penitência",
    "unção dos enfermos",
    "matrimônio católico",
    "casamento na Igreja",
    "nulidade matrimonial",
    "ordem sacerdotal",
    "diaconato",
    "celibato sacerdotal",
    "vocação religiosa",
    "sacramentais",
    "água benta",
    "indulgências",
    "jejum e abstinência",
  ],

  oracoes: [
    "orações católicas",
    "orações católicas tradicionais",
    "oração da manhã",
    "oração da noite",
    "Pai Nosso",
    "Ave Maria",
    "Glória ao Padre",
    "Credo oração",
    "Salve Rainha",
    "Angelus",
    "Regina Caeli",
    "Magnificat",
    "Benedictus",
    "Nunc dimittis",
    "Te Deum",
    "santo rosário",
    "como rezar o rosário",
    "mistérios gozosos",
    "mistérios luminosos",
    "mistérios dolorosos",
    "mistérios gloriosos",
    "terço da misericórdia",
    "coroa das doze estrelas",
    "via-sacra",
    "estações da via-sacra",
    "novena",
    "novena das rosas",
    "novena a Santa Rita",
    "novena a São José",
    "novena ao Sagrado Coração",
    "ladainha de Nossa Senhora",
    "ladainha de São José",
    "ladainha do Sagrado Coração",
    "liturgia das horas",
    "ofício divino",
    "laudes",
    "vésperas",
    "completas",
    "oração de São Francisco",
    "oração a São Miguel Arcanjo",
    "oração ao anjo da guarda",
    "oração pelos falecidos",
    "oração de cura interior",
    "oração de libertação",
    "consagração a Nossa Senhora",
    "consagração ao Imaculado Coração de Maria",
    "primeiras sextas-feiras",
    "primeiros sábados",
    "devoções católicas",
    "escapulário do Carmo",
    "medalha de São Bento",
    "sinal da cruz",
    "bênção da mesa",
  ],

  santos: [
    "santos católicos",
    "vidas dos santos",
    "santo do dia",
    "santo de hoje",
    "hagiografia",
    "processo de canonização",
    "beatificação",
    "mártires cristãos",
    "santos padroeiros",
    "padroeiro do Brasil",
    "Doutores da Igreja",
    "Padres da Igreja",
    "Padres Apostólicos",
    "São Pedro",
    "São Paulo",
    "São José",
    "São João Batista",
    "Santo Estêvão",
    "Santo Agostinho",
    "São Jerônimo",
    "Santo Ambrósio",
    "São Gregório Magno",
    "São Tomás de Aquino",
    "São Boaventura",
    "São Bento",
    "São Francisco de Assis",
    "Santa Clara de Assis",
    "Santo Antônio de Pádua",
    "São Domingos de Gusmão",
    "Santa Catarina de Sena",
    "Santa Teresa de Ávila",
    "São João da Cruz",
    "Santa Teresinha do Menino Jesus",
    "São Francisco Xavier",
    "Santo Inácio de Loyola",
    "São Vicente de Paulo",
    "São Padre Pio",
    "São Maximiliano Kolbe",
    "Santa Edith Stein",
    "Santa Faustina Kowalska",
    "São João Paulo II",
    "Santa Teresa de Calcutá",
    "Santa Dulce dos Pobres",
    "São José de Anchieta",
    "Santo Antônio de Sant'Ana Galvão",
    "Santa Paulina",
    "Santa Rita de Cássia",
    "São Judas Tadeu",
    "São Jorge",
    "São Sebastião",
    "São Bento de Núrsia",
    "Santa Bernadete Soubirous",
    "São Miguel Arcanjo",
    "anjos e arcanjos",
  ],

  maria: [
    "Nossa Senhora",
    "mariologia",
    "dogmas marianos",
    "Maria Mãe de Deus",
    "Theotokos",
    "Imaculada Conceição",
    "Assunção de Nossa Senhora",
    "virgindade perpétua de Maria",
    "por que os católicos rezam para Maria",
    "diferença entre veneração e adoração",
    "aparições marianas aprovadas",
    "Nossa Senhora de Fátima",
    "Nossa Senhora de Lourdes",
    "Nossa Senhora Aparecida",
    "Nossa Senhora do Carmo",
    "Nossa Senhora das Graças",
    "Nossa Senhora de Guadalupe",
    "Nossa Senhora do Perpétuo Socorro",
    "Nossa Senhora Desatadora dos Nós",
    "Coração Imaculado de Maria",
    "medalha milagrosa",
    "mês de maio mariano",
    "Maria mediadora de graças",
    "Maria Mãe da Igreja",
  ],

  liturgia: [
    "liturgia diária",
    "liturgia do dia",
    "leituras de hoje",
    "evangelho do dia",
    "salmo responsorial de hoje",
    "calendário litúrgico",
    "calendário litúrgico 2026",
    "ano litúrgico",
    "tempo do advento",
    "tempo do natal",
    "tempo comum",
    "quarta-feira de cinzas",
    "quaresma",
    "semana santa",
    "tríduo pascal",
    "sexta-feira santa",
    "vigília pascal",
    "tempo pascal",
    "ascensão do Senhor",
    "pentecostes",
    "corpus christi",
    "solenidades e festas",
    "memória dos santos",
    "cores litúrgicas",
    "data da páscoa",
    "quando começa a quaresma",
    "santos do mês",
    "dias de guarda",
    "missa tridentina",
    "canto gregoriano",
    "paramentos litúrgicos",
    "alfaia e vasos sagrados",
    "função do coroinha",
    "ministro extraordinário da comunhão",
  ],

  apologetica: [
    "apologética católica",
    "defesa da fé católica",
    "existe Deus",
    "provas da existência de Deus",
    "cinco vias de Santo Tomás",
    "fé e razão",
    "fé e ciência",
    "por que ser católico",
    "primado de Pedro",
    "sucessão apostólica",
    "infalibilidade papal",
    "autoridade da Igreja",
    "Escritura e Tradição",
    "sola scriptura resposta católica",
    "por que confessar a um sacerdote",
    "por que os católicos veneram imagens",
    "culto dos santos é idolatria",
    "batismo infantil é bíblico",
    "purgatório é bíblico",
    "papado na história",
    "Igreja fundada por Cristo",
    "objeções ao catolicismo",
    "diálogo com protestantes",
    "diálogo com ateus",
    "problema do mal",
    "milagres eucarísticos",
    "Sudário de Turim",
    "história da Igreja",
    "concílios ecumênicos",
    "Concílio de Niceia",
    "Concílio de Trento",
    "Concílio Vaticano I",
    "Concílio Vaticano II",
    "cisma do oriente",
    "reforma protestante",
    "inquisição história real",
    "cruzadas contexto histórico",
    "heresias antigas",
    "arianismo",
    "gnosticismo",
    "pelagianismo",
  ],

  formacao: [
    "curso de catequese",
    "trilhas de formação católica",
    "iniciação à vida cristã",
    "RCIA catecumenato",
    "estudo do catecismo passo a passo",
    "teologia para leigos",
    "teologia dogmática",
    "teologia moral",
    "escatologia católica",
    "cristologia",
    "eclesiologia",
    "patrologia",
    "espiritualidade católica",
    "discernimento vocacional",
    "vida de oração",
    "oração mental",
    "meditação cristã",
    "combate espiritual",
    "direção espiritual",
    "exame de consciência diário",
    "diário espiritual",
    "hábitos de oração diária",
    "crescer na fé",
    "voltar para a Igreja",
    "conversão ao catolicismo",
    "dúvidas sobre a fé católica",
    "perguntas frequentes sobre a Igreja",
    "glossário de termos católicos",
    "documentos do magistério",
    "encíclicas papais",
    "exortações apostólicas",
    "Direito Canônico",
    "código de direito canônico",
    "assistente católico de IA",
    "perguntar sobre a fé católica",
    "notícias católicas",
    "notícias do Vaticano",
    "notícias da Igreja no Brasil",
    "papa notícias",
    "fórum católico",
    "comunidade católica online",
  ],
} as const;

export type Grupo = keyof typeof GRUPOS;

/** Total de termos distintos catalogados (útil em auditoria de conteúdo). */
export const TOTAL_PALAVRAS = new Set(Object.values(GRUPOS).flat()).size;

/**
 * Monta o conteúdo da meta `keywords` de uma página: junta os grupos pedidos,
 * acrescenta termos específicos da rota, remove repetições e limita o tamanho
 * para manter a tag enxuta e relevante.
 */
export function keywordsPara(grupos: Grupo[], extras: string[] = [], limite = 45): string {
  const vistos = new Set<string>();
  const lista: string[] = [];
  for (const termo of [...extras, ...grupos.flatMap((g) => [...GRUPOS[g]])]) {
    const chave = termo.toLowerCase();
    if (vistos.has(chave)) continue;
    vistos.add(chave);
    lista.push(termo);
    if (lista.length >= limite) break;
  }
  return lista.join(", ");
}
