/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SantosRouteImport } from './routes/santos'
import { Route as SacramentosRouteImport } from './routes/sacramentos'
import { Route as OracoesRouteImport } from './routes/oracoes'
import { Route as MariaRouteImport } from './routes/maria'
import { Route as FeCatolicaRouteImport } from './routes/fe-catolica'
import { Route as DoutoresDaIgrejaRouteImport } from './routes/doutores-da-igreja'
import { Route as CatecismoRouteImport } from './routes/catecismo'
import { Route as CalendarioLiturgicoRouteImport } from './routes/calendario-liturgico'
import { Route as BibliaRouteImport } from './routes/biblia'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as ApologeticaRouteImport } from './routes/apologetica'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OracoesViaSacraRouteImport } from './routes/oracoes.via-sacra'
import { Route as OracoesRosarioRouteImport } from './routes/oracoes.rosario'
import { Route as OracoesNovenasRouteImport } from './routes/oracoes.novenas'
import { Route as OracoesLiturgiaDasHorasRouteImport } from './routes/oracoes.liturgia-das-horas'
import { Route as CatecismoParteRouteImport } from './routes/catecismo.$parte'
import { Route as BibliaLivroRouteImport } from './routes/biblia.$livro'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as OracoesNovenasSlugRouteImport } from './routes/oracoes.novenas.$slug'
import { Route as BibliaLivroCapituloRouteImport } from './routes/biblia.$livro.$capitulo'

const SantosRoute = SantosRouteImport.update({
  id: '/santos',
  path: '/santos',
  getParentRoute: () => rootRouteImport,
} as any)
const SacramentosRoute = SacramentosRouteImport.update({
  id: '/sacramentos',
  path: '/sacramentos',
  getParentRoute: () => rootRouteImport,
} as any)
const OracoesRoute = OracoesRouteImport.update({
  id: '/oracoes',
  path: '/oracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MariaRoute = MariaRouteImport.update({
  id: '/maria',
  path: '/maria',
  getParentRoute: () => rootRouteImport,
} as any)
const FeCatolicaRoute = FeCatolicaRouteImport.update({
  id: '/fe-catolica',
  path: '/fe-catolica',
  getParentRoute: () => rootRouteImport,
} as any)
const DoutoresDaIgrejaRoute = DoutoresDaIgrejaRouteImport.update({
  id: '/doutores-da-igreja',
  path: '/doutores-da-igreja',
  getParentRoute: () => rootRouteImport,
} as any)
const CatecismoRoute = CatecismoRouteImport.update({
  id: '/catecismo',
  path: '/catecismo',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioLiturgicoRoute = CalendarioLiturgicoRouteImport.update({
  id: '/calendario-liturgico',
  path: '/calendario-liturgico',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaRoute = BibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const ApologeticaRoute = ApologeticaRouteImport.update({
  id: '/apologetica',
  path: '/apologetica',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OracoesViaSacraRoute = OracoesViaSacraRouteImport.update({
  id: '/via-sacra',
  path: '/via-sacra',
  getParentRoute: () => OracoesRoute,
} as any)
const OracoesRosarioRoute = OracoesRosarioRouteImport.update({
  id: '/rosario',
  path: '/rosario',
  getParentRoute: () => OracoesRoute,
} as any)
const OracoesNovenasRoute = OracoesNovenasRouteImport.update({
  id: '/novenas',
  path: '/novenas',
  getParentRoute: () => OracoesRoute,
} as any)
const OracoesLiturgiaDasHorasRoute = OracoesLiturgiaDasHorasRouteImport.update({
  id: '/liturgia-das-horas',
  path: '/liturgia-das-horas',
  getParentRoute: () => OracoesRoute,
} as any)
const CatecismoParteRoute = CatecismoParteRouteImport.update({
  id: '/$parte',
  path: '/$parte',
  getParentRoute: () => CatecismoRoute,
} as any)
const BibliaLivroRoute = BibliaLivroRouteImport.update({
  id: '/$livro',
  path: '/$livro',
  getParentRoute: () => BibliaRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const OracoesNovenasSlugRoute = OracoesNovenasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OracoesNovenasRoute,
} as any)
const BibliaLivroCapituloRoute = BibliaLivroCapituloRouteImport.update({
  id: '/$capitulo',
  path: '/$capitulo',
  getParentRoute: () => BibliaLivroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apologetica': typeof ApologeticaRoute
  '/assistente': typeof AssistenteRoute
  '/biblia': typeof BibliaRouteWithChildren
  '/calendario-liturgico': typeof CalendarioLiturgicoRoute
  '/catecismo': typeof CatecismoRouteWithChildren
  '/doutores-da-igreja': typeof DoutoresDaIgrejaRoute
  '/fe-catolica': typeof FeCatolicaRoute
  '/maria': typeof MariaRoute
  '/oracoes': typeof OracoesRouteWithChildren
  '/sacramentos': typeof SacramentosRoute
  '/santos': typeof SantosRoute
  '/api/chat': typeof ApiChatRoute
  '/biblia/$livro': typeof BibliaLivroRouteWithChildren
  '/catecismo/$parte': typeof CatecismoParteRoute
  '/oracoes/liturgia-das-horas': typeof OracoesLiturgiaDasHorasRoute
  '/oracoes/novenas': typeof OracoesNovenasRouteWithChildren
  '/oracoes/rosario': typeof OracoesRosarioRoute
  '/oracoes/via-sacra': typeof OracoesViaSacraRoute
  '/biblia/$livro/$capitulo': typeof BibliaLivroCapituloRoute
  '/oracoes/novenas/$slug': typeof OracoesNovenasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apologetica': typeof ApologeticaRoute
  '/assistente': typeof AssistenteRoute
  '/biblia': typeof BibliaRouteWithChildren
  '/calendario-liturgico': typeof CalendarioLiturgicoRoute
  '/catecismo': typeof CatecismoRouteWithChildren
  '/doutores-da-igreja': typeof DoutoresDaIgrejaRoute
  '/fe-catolica': typeof FeCatolicaRoute
  '/maria': typeof MariaRoute
  '/oracoes': typeof OracoesRouteWithChildren
  '/sacramentos': typeof SacramentosRoute
  '/santos': typeof SantosRoute
  '/api/chat': typeof ApiChatRoute
  '/biblia/$livro': typeof BibliaLivroRouteWithChildren
  '/catecismo/$parte': typeof CatecismoParteRoute
  '/oracoes/liturgia-das-horas': typeof OracoesLiturgiaDasHorasRoute
  '/oracoes/novenas': typeof OracoesNovenasRouteWithChildren
  '/oracoes/rosario': typeof OracoesRosarioRoute
  '/oracoes/via-sacra': typeof OracoesViaSacraRoute
  '/biblia/$livro/$capitulo': typeof BibliaLivroCapituloRoute
  '/oracoes/novenas/$slug': typeof OracoesNovenasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apologetica': typeof ApologeticaRoute
  '/assistente': typeof AssistenteRoute
  '/biblia': typeof BibliaRouteWithChildren
  '/calendario-liturgico': typeof CalendarioLiturgicoRoute
  '/catecismo': typeof CatecismoRouteWithChildren
  '/doutores-da-igreja': typeof DoutoresDaIgrejaRoute
  '/fe-catolica': typeof FeCatolicaRoute
  '/maria': typeof MariaRoute
  '/oracoes': typeof OracoesRouteWithChildren
  '/sacramentos': typeof SacramentosRoute
  '/santos': typeof SantosRoute
  '/api/chat': typeof ApiChatRoute
  '/biblia/$livro': typeof BibliaLivroRouteWithChildren
  '/catecismo/$parte': typeof CatecismoParteRoute
  '/oracoes/liturgia-das-horas': typeof OracoesLiturgiaDasHorasRoute
  '/oracoes/novenas': typeof OracoesNovenasRouteWithChildren
  '/oracoes/rosario': typeof OracoesRosarioRoute
  '/oracoes/via-sacra': typeof OracoesViaSacraRoute
  '/biblia/$livro/$capitulo': typeof BibliaLivroCapituloRoute
  '/oracoes/novenas/$slug': typeof OracoesNovenasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apologetica'
    | '/assistente'
    | '/biblia'
    | '/calendario-liturgico'
    | '/catecismo'
    | '/doutores-da-igreja'
    | '/fe-catolica'
    | '/maria'
    | '/oracoes'
    | '/sacramentos'
    | '/santos'
    | '/api/chat'
    | '/biblia/$livro'
    | '/catecismo/$parte'
    | '/oracoes/liturgia-das-horas'
    | '/oracoes/novenas'
    | '/oracoes/rosario'
    | '/oracoes/via-sacra'
    | '/biblia/$livro/$capitulo'
    | '/oracoes/novenas/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apologetica'
    | '/assistente'
    | '/biblia'
    | '/calendario-liturgico'
    | '/catecismo'
    | '/doutores-da-igreja'
    | '/fe-catolica'
    | '/maria'
    | '/oracoes'
    | '/sacramentos'
    | '/santos'
    | '/api/chat'
    | '/biblia/$livro'
    | '/catecismo/$parte'
    | '/oracoes/liturgia-das-horas'
    | '/oracoes/novenas'
    | '/oracoes/rosario'
    | '/oracoes/via-sacra'
    | '/biblia/$livro/$capitulo'
    | '/oracoes/novenas/$slug'
  id:
    | '__root__'
    | '/'
    | '/apologetica'
    | '/assistente'
    | '/biblia'
    | '/calendario-liturgico'
    | '/catecismo'
    | '/doutores-da-igreja'
    | '/fe-catolica'
    | '/maria'
    | '/oracoes'
    | '/sacramentos'
    | '/santos'
    | '/api/chat'
    | '/biblia/$livro'
    | '/catecismo/$parte'
    | '/oracoes/liturgia-das-horas'
    | '/oracoes/novenas'
    | '/oracoes/rosario'
    | '/oracoes/via-sacra'
    | '/biblia/$livro/$capitulo'
    | '/oracoes/novenas/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApologeticaRoute: typeof ApologeticaRoute
  AssistenteRoute: typeof AssistenteRoute
  BibliaRoute: typeof BibliaRouteWithChildren
  CalendarioLiturgicoRoute: typeof CalendarioLiturgicoRoute
  CatecismoRoute: typeof CatecismoRouteWithChildren
  DoutoresDaIgrejaRoute: typeof DoutoresDaIgrejaRoute
  FeCatolicaRoute: typeof FeCatolicaRoute
  MariaRoute: typeof MariaRoute
  OracoesRoute: typeof OracoesRouteWithChildren
  SacramentosRoute: typeof SacramentosRoute
  SantosRoute: typeof SantosRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/santos': {
      id: '/santos'
      path: '/santos'
      fullPath: '/santos'
      preLoaderRoute: typeof SantosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sacramentos': {
      id: '/sacramentos'
      path: '/sacramentos'
      fullPath: '/sacramentos'
      preLoaderRoute: typeof SacramentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracoes': {
      id: '/oracoes'
      path: '/oracoes'
      fullPath: '/oracoes'
      preLoaderRoute: typeof OracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maria': {
      id: '/maria'
      path: '/maria'
      fullPath: '/maria'
      preLoaderRoute: typeof MariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fe-catolica': {
      id: '/fe-catolica'
      path: '/fe-catolica'
      fullPath: '/fe-catolica'
      preLoaderRoute: typeof FeCatolicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doutores-da-igreja': {
      id: '/doutores-da-igreja'
      path: '/doutores-da-igreja'
      fullPath: '/doutores-da-igreja'
      preLoaderRoute: typeof DoutoresDaIgrejaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catecismo': {
      id: '/catecismo'
      path: '/catecismo'
      fullPath: '/catecismo'
      preLoaderRoute: typeof CatecismoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario-liturgico': {
      id: '/calendario-liturgico'
      path: '/calendario-liturgico'
      fullPath: '/calendario-liturgico'
      preLoaderRoute: typeof CalendarioLiturgicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia': {
      id: '/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof BibliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apologetica': {
      id: '/apologetica'
      path: '/apologetica'
      fullPath: '/apologetica'
      preLoaderRoute: typeof ApologeticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracoes/via-sacra': {
      id: '/oracoes/via-sacra'
      path: '/via-sacra'
      fullPath: '/oracoes/via-sacra'
      preLoaderRoute: typeof OracoesViaSacraRouteImport
      parentRoute: typeof OracoesRoute
    }
    '/oracoes/rosario': {
      id: '/oracoes/rosario'
      path: '/rosario'
      fullPath: '/oracoes/rosario'
      preLoaderRoute: typeof OracoesRosarioRouteImport
      parentRoute: typeof OracoesRoute
    }
    '/oracoes/novenas': {
      id: '/oracoes/novenas'
      path: '/novenas'
      fullPath: '/oracoes/novenas'
      preLoaderRoute: typeof OracoesNovenasRouteImport
      parentRoute: typeof OracoesRoute
    }
    '/oracoes/liturgia-das-horas': {
      id: '/oracoes/liturgia-das-horas'
      path: '/liturgia-das-horas'
      fullPath: '/oracoes/liturgia-das-horas'
      preLoaderRoute: typeof OracoesLiturgiaDasHorasRouteImport
      parentRoute: typeof OracoesRoute
    }
    '/catecismo/$parte': {
      id: '/catecismo/$parte'
      path: '/$parte'
      fullPath: '/catecismo/$parte'
      preLoaderRoute: typeof CatecismoParteRouteImport
      parentRoute: typeof CatecismoRoute
    }
    '/biblia/$livro': {
      id: '/biblia/$livro'
      path: '/$livro'
      fullPath: '/biblia/$livro'
      preLoaderRoute: typeof BibliaLivroRouteImport
      parentRoute: typeof BibliaRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracoes/novenas/$slug': {
      id: '/oracoes/novenas/$slug'
      path: '/$slug'
      fullPath: '/oracoes/novenas/$slug'
      preLoaderRoute: typeof OracoesNovenasSlugRouteImport
      parentRoute: typeof OracoesNovenasRoute
    }
    '/biblia/$livro/$capitulo': {
      id: '/biblia/$livro/$capitulo'
      path: '/$capitulo'
      fullPath: '/biblia/$livro/$capitulo'
      preLoaderRoute: typeof BibliaLivroCapituloRouteImport
      parentRoute: typeof BibliaLivroRoute
    }
  }
}

interface BibliaLivroRouteChildren {
  BibliaLivroCapituloRoute: typeof BibliaLivroCapituloRoute
}

const BibliaLivroRouteChildren: BibliaLivroRouteChildren = {
  BibliaLivroCapituloRoute: BibliaLivroCapituloRoute,
}

const BibliaLivroRouteWithChildren = BibliaLivroRoute._addFileChildren(
  BibliaLivroRouteChildren,
)

interface BibliaRouteChildren {
  BibliaLivroRoute: typeof BibliaLivroRouteWithChildren
}

const BibliaRouteChildren: BibliaRouteChildren = {
  BibliaLivroRoute: BibliaLivroRouteWithChildren,
}

const BibliaRouteWithChildren =
  BibliaRoute._addFileChildren(BibliaRouteChildren)

interface CatecismoRouteChildren {
  CatecismoParteRoute: typeof CatecismoParteRoute
}

const CatecismoRouteChildren: CatecismoRouteChildren = {
  CatecismoParteRoute: CatecismoParteRoute,
}

const CatecismoRouteWithChildren = CatecismoRoute._addFileChildren(
  CatecismoRouteChildren,
)

interface OracoesNovenasRouteChildren {
  OracoesNovenasSlugRoute: typeof OracoesNovenasSlugRoute
}

const OracoesNovenasRouteChildren: OracoesNovenasRouteChildren = {
  OracoesNovenasSlugRoute: OracoesNovenasSlugRoute,
}

const OracoesNovenasRouteWithChildren = OracoesNovenasRoute._addFileChildren(
  OracoesNovenasRouteChildren,
)

interface OracoesRouteChildren {
  OracoesLiturgiaDasHorasRoute: typeof OracoesLiturgiaDasHorasRoute
  OracoesNovenasRoute: typeof OracoesNovenasRouteWithChildren
  OracoesRosarioRoute: typeof OracoesRosarioRoute
  OracoesViaSacraRoute: typeof OracoesViaSacraRoute
}

const OracoesRouteChildren: OracoesRouteChildren = {
  OracoesLiturgiaDasHorasRoute: OracoesLiturgiaDasHorasRoute,
  OracoesNovenasRoute: OracoesNovenasRouteWithChildren,
  OracoesRosarioRoute: OracoesRosarioRoute,
  OracoesViaSacraRoute: OracoesViaSacraRoute,
}

const OracoesRouteWithChildren =
  OracoesRoute._addFileChildren(OracoesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApologeticaRoute: ApologeticaRoute,
  AssistenteRoute: AssistenteRoute,
  BibliaRoute: BibliaRouteWithChildren,
  CalendarioLiturgicoRoute: CalendarioLiturgicoRoute,
  CatecismoRoute: CatecismoRouteWithChildren,
  DoutoresDaIgrejaRoute: DoutoresDaIgrejaRoute,
  FeCatolicaRoute: FeCatolicaRoute,
  MariaRoute: MariaRoute,
  OracoesRoute: OracoesRouteWithChildren,
  SacramentosRoute: SacramentosRoute,
  SantosRoute: SantosRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
