/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SophiaDiagnosticoRouteImport } from './routes/sophia-diagnostico'
import { Route as SantosRouteImport } from './routes/santos'
import { Route as SacramentosRouteImport } from './routes/sacramentos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OracoesRouteImport } from './routes/oracoes'
import { Route as MariaRouteImport } from './routes/maria'
import { Route as FeCatolicaRouteImport } from './routes/fe-catolica'
import { Route as DoutoresDaIgrejaRouteImport } from './routes/doutores-da-igreja'
import { Route as CoroinhasRouteImport } from './routes/coroinhas'
import { Route as CatecismoRouteImport } from './routes/catecismo'
import { Route as CalendarioLiturgicoRouteImport } from './routes/calendario-liturgico'
import { Route as BibliaRouteImport } from './routes/biblia'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as ApologeticaRouteImport } from './routes/apologetica'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliaIndexRouteImport } from './routes/biblia.index'
import { Route as SantosSlugRouteImport } from './routes/santos.$slug'
import { Route as OracoesViaSacraRouteImport } from './routes/oracoes.via-sacra'
import { Route as OracoesTercoMisericordiaRouteImport } from './routes/oracoes.terco-misericordia'
import { Route as OracoesRosarioRouteImport } from './routes/oracoes.rosario'
import { Route as OracoesNovenasRouteImport } from './routes/oracoes.novenas'
import { Route as OracoesLiturgiaDasHorasRouteImport } from './routes/oracoes.liturgia-das-horas'
import { Route as CatecismoParteRouteImport } from './routes/catecismo.$parte'
import { Route as BibliaLeiturasRouteImport } from './routes/biblia.leituras'
import { Route as BibliaLivroRouteImport } from './routes/biblia.$livro'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as BibliaLivroIndexRouteImport } from './routes/biblia.$livro.index'
import { Route as OracoesNovenasSlugRouteImport } from './routes/oracoes.novenas.$slug'
import { Route as BibliaLivroCapituloRouteImport } from './routes/biblia.$livro.$capitulo'

const SophiaDiagnosticoRoute = SophiaDiagnosticoRouteImport.update({
  id: '/sophia-diagnostico',
  path: '/sophia-diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const SantosRoute = SantosRouteImport.update({
  id: '/santos',
  path: '/santos',
  getParentRoute: () => rootRouteImport,
} as any)
const SacramentosRoute = SacramentosRouteImport.update({
  id: '/sacramentos',
  path: '/sacramentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OracoesRoute = OracoesRouteImport.update({
  id: '/oracoes',
  path: '/oracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MariaRoute = MariaRouteImport.update({
  id: '/maria',
  path: '/maria',
  getParentRoute: () => rootRouteImport,
} as any)
const FeCatolicaRoute = FeCatolicaRouteImport.update({
  id: '/fe-catolica',
  path: '/fe-catolica',
  getParentRoute: () => rootRouteImport,
} as any)
const DoutoresDaIgrejaRoute = DoutoresDaIgrejaRouteImport.update({
  id: '/doutores-da-igreja',
  path: '/doutores-da-igreja',
  getParentRoute: () => rootRouteImport,
} as any)
const CoroinhasRoute = CoroinhasRouteImport.update({
  id: '/coroinhas',
  path: '/coroinhas',
  getParentRoute: () => rootRouteImport,
} as any)
const CatecismoRoute = CatecismoRouteImport.update({
  id: '/catecismo',
  path: '/catecismo',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioLiturgicoRoute = CalendarioLiturgicoRouteImport.update({
  id: '/calendario-liturgico',
  path: '/calendario-liturgico',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaRoute = BibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const ApologeticaRoute = ApologeticaRouteImport.update({
  id: '/apologetica',
  path: '/apologetica',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaIndexRoute = BibliaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliaRoute,
} as any)
const SantosSlugRoute = SantosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SantosRoute,
} as any)
const OracoesViaSacraRoute = OracoesViaSacraRouteImport.update({
  id: '/via-sacra',
  path: '/via-sacra',
  getParentRoute: () => OracoesRoute,
} as any)
const OracoesTercoMisericordiaRoute =
  OracoesTercoMisericordiaRouteImport.update({
    id: '/terco-misericordia',
    path: '/terco-misericordia',
    getParentRoute: () => OracoesRoute,
  } as any)
const OracoesRosarioRoute = OracoesRosarioRouteImport.update({
  id: '/rosario',
  path: '/rosario',
  getParentRoute: () => OracoesRoute,
} as any)
const OracoesNovenasRoute = OracoesNovenasRouteImport.update({
  id: '/novenas',
  path: '/novenas',
  getParentRoute: () => OracoesRoute,
} as any)
const OracoesLiturgiaDasHorasRoute = OracoesLiturgiaDasHorasRouteImport.update({
  id: '/liturgia-das-horas',
  path: '/liturgia-das-horas',
  getParentRoute: () => OracoesRoute,
} as any)
const CatecismoParteRoute = CatecismoParteRouteImport.update({
  id: '/$parte',
  path: '/$parte',
  getParentRoute: () => CatecismoRoute,
} as any)
const BibliaLeiturasRoute = BibliaLeiturasRouteImport.update({
  id: '/leituras',
  path: '/leituras',
  getParentRoute: () => BibliaRoute,
} as any)
const BibliaLivroRoute = BibliaLivroRouteImport.update({
  id: '/$livro',
  path: '/$livro',
  getParentRoute: () => BibliaRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BibliaLivroIndexRoute = BibliaLivroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliaLivroRoute,
} as any)
const OracoesNovenasSlugRoute = OracoesNovenasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OracoesNovenasRoute,
} as any)
const BibliaLivroCapituloRoute = BibliaLivroCapituloRouteImport.update({
  id: '/$capitulo',
  path: '/$capitulo',
  getParentRoute: () => BibliaLivroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apologetica': typeof ApologeticaRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/biblia': typeof BibliaRouteWithChildren
  '/calendario-liturgico': typeof CalendarioLiturgicoRoute
  '/catecismo': typeof CatecismoRouteWithChildren
  '/coroinhas': typeof CoroinhasRoute
  '/doutores-da-igreja': typeof DoutoresDaIgrejaRoute
  '/fe-catolica': typeof FeCatolicaRoute
  '/maria': typeof MariaRoute
  '/oracoes': typeof OracoesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sacramentos': typeof SacramentosRoute
  '/santos': typeof SantosRouteWithChildren
  '/sophia-diagnostico': typeof SophiaDiagnosticoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/api/chat': typeof ApiChatRoute
  '/biblia/$livro': typeof BibliaLivroRouteWithChildren
  '/biblia/leituras': typeof BibliaLeiturasRoute
  '/catecismo/$parte': typeof CatecismoParteRoute
  '/oracoes/liturgia-das-horas': typeof OracoesLiturgiaDasHorasRoute
  '/oracoes/novenas': typeof OracoesNovenasRouteWithChildren
  '/oracoes/rosario': typeof OracoesRosarioRoute
  '/oracoes/terco-misericordia': typeof OracoesTercoMisericordiaRoute
  '/oracoes/via-sacra': typeof OracoesViaSacraRoute
  '/santos/$slug': typeof SantosSlugRoute
  '/biblia/': typeof BibliaIndexRoute
  '/biblia/$livro/$capitulo': typeof BibliaLivroCapituloRoute
  '/oracoes/novenas/$slug': typeof OracoesNovenasSlugRoute
  '/biblia/$livro/': typeof BibliaLivroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apologetica': typeof ApologeticaRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/calendario-liturgico': typeof CalendarioLiturgicoRoute
  '/catecismo': typeof CatecismoRouteWithChildren
  '/coroinhas': typeof CoroinhasRoute
  '/doutores-da-igreja': typeof DoutoresDaIgrejaRoute
  '/fe-catolica': typeof FeCatolicaRoute
  '/maria': typeof MariaRoute
  '/oracoes': typeof OracoesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sacramentos': typeof SacramentosRoute
  '/santos': typeof SantosRouteWithChildren
  '/sophia-diagnostico': typeof SophiaDiagnosticoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/api/chat': typeof ApiChatRoute
  '/biblia/leituras': typeof BibliaLeiturasRoute
  '/catecismo/$parte': typeof CatecismoParteRoute
  '/oracoes/liturgia-das-horas': typeof OracoesLiturgiaDasHorasRoute
  '/oracoes/novenas': typeof OracoesNovenasRouteWithChildren
  '/oracoes/rosario': typeof OracoesRosarioRoute
  '/oracoes/terco-misericordia': typeof OracoesTercoMisericordiaRoute
  '/oracoes/via-sacra': typeof OracoesViaSacraRoute
  '/santos/$slug': typeof SantosSlugRoute
  '/biblia': typeof BibliaIndexRoute
  '/biblia/$livro/$capitulo': typeof BibliaLivroCapituloRoute
  '/oracoes/novenas/$slug': typeof OracoesNovenasSlugRoute
  '/biblia/$livro': typeof BibliaLivroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apologetica': typeof ApologeticaRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/biblia': typeof BibliaRouteWithChildren
  '/calendario-liturgico': typeof CalendarioLiturgicoRoute
  '/catecismo': typeof CatecismoRouteWithChildren
  '/coroinhas': typeof CoroinhasRoute
  '/doutores-da-igreja': typeof DoutoresDaIgrejaRoute
  '/fe-catolica': typeof FeCatolicaRoute
  '/maria': typeof MariaRoute
  '/oracoes': typeof OracoesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sacramentos': typeof SacramentosRoute
  '/santos': typeof SantosRouteWithChildren
  '/sophia-diagnostico': typeof SophiaDiagnosticoRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/api/chat': typeof ApiChatRoute
  '/biblia/$livro': typeof BibliaLivroRouteWithChildren
  '/biblia/leituras': typeof BibliaLeiturasRoute
  '/catecismo/$parte': typeof CatecismoParteRoute
  '/oracoes/liturgia-das-horas': typeof OracoesLiturgiaDasHorasRoute
  '/oracoes/novenas': typeof OracoesNovenasRouteWithChildren
  '/oracoes/rosario': typeof OracoesRosarioRoute
  '/oracoes/terco-misericordia': typeof OracoesTercoMisericordiaRoute
  '/oracoes/via-sacra': typeof OracoesViaSacraRoute
  '/santos/$slug': typeof SantosSlugRoute
  '/biblia/': typeof BibliaIndexRoute
  '/biblia/$livro/$capitulo': typeof BibliaLivroCapituloRoute
  '/oracoes/novenas/$slug': typeof OracoesNovenasSlugRoute
  '/biblia/$livro/': typeof BibliaLivroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apologetica'
    | '/assistente'
    | '/auth'
    | '/biblia'
    | '/calendario-liturgico'
    | '/catecismo'
    | '/coroinhas'
    | '/doutores-da-igreja'
    | '/fe-catolica'
    | '/maria'
    | '/oracoes'
    | '/reset-password'
    | '/sacramentos'
    | '/santos'
    | '/sophia-diagnostico'
    | '/painel'
    | '/api/chat'
    | '/biblia/$livro'
    | '/biblia/leituras'
    | '/catecismo/$parte'
    | '/oracoes/liturgia-das-horas'
    | '/oracoes/novenas'
    | '/oracoes/rosario'
    | '/oracoes/terco-misericordia'
    | '/oracoes/via-sacra'
    | '/santos/$slug'
    | '/biblia/'
    | '/biblia/$livro/$capitulo'
    | '/oracoes/novenas/$slug'
    | '/biblia/$livro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apologetica'
    | '/assistente'
    | '/auth'
    | '/calendario-liturgico'
    | '/catecismo'
    | '/coroinhas'
    | '/doutores-da-igreja'
    | '/fe-catolica'
    | '/maria'
    | '/oracoes'
    | '/reset-password'
    | '/sacramentos'
    | '/santos'
    | '/sophia-diagnostico'
    | '/painel'
    | '/api/chat'
    | '/biblia/leituras'
    | '/catecismo/$parte'
    | '/oracoes/liturgia-das-horas'
    | '/oracoes/novenas'
    | '/oracoes/rosario'
    | '/oracoes/terco-misericordia'
    | '/oracoes/via-sacra'
    | '/santos/$slug'
    | '/biblia'
    | '/biblia/$livro/$capitulo'
    | '/oracoes/novenas/$slug'
    | '/biblia/$livro'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apologetica'
    | '/assistente'
    | '/auth'
    | '/biblia'
    | '/calendario-liturgico'
    | '/catecismo'
    | '/coroinhas'
    | '/doutores-da-igreja'
    | '/fe-catolica'
    | '/maria'
    | '/oracoes'
    | '/reset-password'
    | '/sacramentos'
    | '/santos'
    | '/sophia-diagnostico'
    | '/_authenticated/painel'
    | '/api/chat'
    | '/biblia/$livro'
    | '/biblia/leituras'
    | '/catecismo/$parte'
    | '/oracoes/liturgia-das-horas'
    | '/oracoes/novenas'
    | '/oracoes/rosario'
    | '/oracoes/terco-misericordia'
    | '/oracoes/via-sacra'
    | '/santos/$slug'
    | '/biblia/'
    | '/biblia/$livro/$capitulo'
    | '/oracoes/novenas/$slug'
    | '/biblia/$livro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApologeticaRoute: typeof ApologeticaRoute
  AssistenteRoute: typeof AssistenteRoute
  AuthRoute: typeof AuthRoute
  BibliaRoute: typeof BibliaRouteWithChildren
  CalendarioLiturgicoRoute: typeof CalendarioLiturgicoRoute
  CatecismoRoute: typeof CatecismoRouteWithChildren
  CoroinhasRoute: typeof CoroinhasRoute
  DoutoresDaIgrejaRoute: typeof DoutoresDaIgrejaRoute
  FeCatolicaRoute: typeof FeCatolicaRoute
  MariaRoute: typeof MariaRoute
  OracoesRoute: typeof OracoesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SacramentosRoute: typeof SacramentosRoute
  SantosRoute: typeof SantosRouteWithChildren
  SophiaDiagnosticoRoute: typeof SophiaDiagnosticoRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sophia-diagnostico': {
      id: '/sophia-diagnostico'
      path: '/sophia-diagnostico'
      fullPath: '/sophia-diagnostico'
      preLoaderRoute: typeof SophiaDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santos': {
      id: '/santos'
      path: '/santos'
      fullPath: '/santos'
      preLoaderRoute: typeof SantosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sacramentos': {
      id: '/sacramentos'
      path: '/sacramentos'
      fullPath: '/sacramentos'
      preLoaderRoute: typeof SacramentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracoes': {
      id: '/oracoes'
      path: '/oracoes'
      fullPath: '/oracoes'
      preLoaderRoute: typeof OracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maria': {
      id: '/maria'
      path: '/maria'
      fullPath: '/maria'
      preLoaderRoute: typeof MariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fe-catolica': {
      id: '/fe-catolica'
      path: '/fe-catolica'
      fullPath: '/fe-catolica'
      preLoaderRoute: typeof FeCatolicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doutores-da-igreja': {
      id: '/doutores-da-igreja'
      path: '/doutores-da-igreja'
      fullPath: '/doutores-da-igreja'
      preLoaderRoute: typeof DoutoresDaIgrejaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coroinhas': {
      id: '/coroinhas'
      path: '/coroinhas'
      fullPath: '/coroinhas'
      preLoaderRoute: typeof CoroinhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catecismo': {
      id: '/catecismo'
      path: '/catecismo'
      fullPath: '/catecismo'
      preLoaderRoute: typeof CatecismoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario-liturgico': {
      id: '/calendario-liturgico'
      path: '/calendario-liturgico'
      fullPath: '/calendario-liturgico'
      preLoaderRoute: typeof CalendarioLiturgicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia': {
      id: '/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof BibliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apologetica': {
      id: '/apologetica'
      path: '/apologetica'
      fullPath: '/apologetica'
      preLoaderRoute: typeof ApologeticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia/': {
      id: '/biblia/'
      path: '/'
      fullPath: '/biblia/'
      preLoaderRoute: typeof BibliaIndexRouteImport
      parentRoute: typeof BibliaRoute
    }
    '/santos/$slug': {
      id: '/santos/$slug'
      path: '/$slug'
      fullPath: '/santos/$slug'
      preLoaderRoute: typeof SantosSlugRouteImport
      parentRoute: typeof SantosRoute
    }
    '/oracoes/via-sacra': {
      id: '/oracoes/via-sacra'
      path: '/via-sacra'
      fullPath: '/oracoes/via-sacra'
      preLoaderRoute: typeof OracoesViaSacraRouteImport
      parentRoute: typeof OracoesRoute
    }
    '/oracoes/terco-misericordia': {
      id: '/oracoes/terco-misericordia'
      path: '/terco-misericordia'
      fullPath: '/oracoes/terco-misericordia'
      preLoaderRoute: typeof OracoesTercoMisericordiaRouteImport
      parentRoute: typeof OracoesRoute
    }
    '/oracoes/rosario': {
      id: '/oracoes/rosario'
      path: '/rosario'
      fullPath: '/oracoes/rosario'
      preLoaderRoute: typeof OracoesRosarioRouteImport
      parentRoute: typeof OracoesRoute
    }
    '/oracoes/novenas': {
      id: '/oracoes/novenas'
      path: '/novenas'
      fullPath: '/oracoes/novenas'
      preLoaderRoute: typeof OracoesNovenasRouteImport
      parentRoute: typeof OracoesRoute
    }
    '/oracoes/liturgia-das-horas': {
      id: '/oracoes/liturgia-das-horas'
      path: '/liturgia-das-horas'
      fullPath: '/oracoes/liturgia-das-horas'
      preLoaderRoute: typeof OracoesLiturgiaDasHorasRouteImport
      parentRoute: typeof OracoesRoute
    }
    '/catecismo/$parte': {
      id: '/catecismo/$parte'
      path: '/$parte'
      fullPath: '/catecismo/$parte'
      preLoaderRoute: typeof CatecismoParteRouteImport
      parentRoute: typeof CatecismoRoute
    }
    '/biblia/leituras': {
      id: '/biblia/leituras'
      path: '/leituras'
      fullPath: '/biblia/leituras'
      preLoaderRoute: typeof BibliaLeiturasRouteImport
      parentRoute: typeof BibliaRoute
    }
    '/biblia/$livro': {
      id: '/biblia/$livro'
      path: '/$livro'
      fullPath: '/biblia/$livro'
      preLoaderRoute: typeof BibliaLivroRouteImport
      parentRoute: typeof BibliaRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/biblia/$livro/': {
      id: '/biblia/$livro/'
      path: '/'
      fullPath: '/biblia/$livro/'
      preLoaderRoute: typeof BibliaLivroIndexRouteImport
      parentRoute: typeof BibliaLivroRoute
    }
    '/oracoes/novenas/$slug': {
      id: '/oracoes/novenas/$slug'
      path: '/$slug'
      fullPath: '/oracoes/novenas/$slug'
      preLoaderRoute: typeof OracoesNovenasSlugRouteImport
      parentRoute: typeof OracoesNovenasRoute
    }
    '/biblia/$livro/$capitulo': {
      id: '/biblia/$livro/$capitulo'
      path: '/$capitulo'
      fullPath: '/biblia/$livro/$capitulo'
      preLoaderRoute: typeof BibliaLivroCapituloRouteImport
      parentRoute: typeof BibliaLivroRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BibliaLivroRouteChildren {
  BibliaLivroCapituloRoute: typeof BibliaLivroCapituloRoute
  BibliaLivroIndexRoute: typeof BibliaLivroIndexRoute
}

const BibliaLivroRouteChildren: BibliaLivroRouteChildren = {
  BibliaLivroCapituloRoute: BibliaLivroCapituloRoute,
  BibliaLivroIndexRoute: BibliaLivroIndexRoute,
}

const BibliaLivroRouteWithChildren = BibliaLivroRoute._addFileChildren(
  BibliaLivroRouteChildren,
)

interface BibliaRouteChildren {
  BibliaLivroRoute: typeof BibliaLivroRouteWithChildren
  BibliaLeiturasRoute: typeof BibliaLeiturasRoute
  BibliaIndexRoute: typeof BibliaIndexRoute
}

const BibliaRouteChildren: BibliaRouteChildren = {
  BibliaLivroRoute: BibliaLivroRouteWithChildren,
  BibliaLeiturasRoute: BibliaLeiturasRoute,
  BibliaIndexRoute: BibliaIndexRoute,
}

const BibliaRouteWithChildren =
  BibliaRoute._addFileChildren(BibliaRouteChildren)

interface CatecismoRouteChildren {
  CatecismoParteRoute: typeof CatecismoParteRoute
}

const CatecismoRouteChildren: CatecismoRouteChildren = {
  CatecismoParteRoute: CatecismoParteRoute,
}

const CatecismoRouteWithChildren = CatecismoRoute._addFileChildren(
  CatecismoRouteChildren,
)

interface OracoesNovenasRouteChildren {
  OracoesNovenasSlugRoute: typeof OracoesNovenasSlugRoute
}

const OracoesNovenasRouteChildren: OracoesNovenasRouteChildren = {
  OracoesNovenasSlugRoute: OracoesNovenasSlugRoute,
}

const OracoesNovenasRouteWithChildren = OracoesNovenasRoute._addFileChildren(
  OracoesNovenasRouteChildren,
)

interface OracoesRouteChildren {
  OracoesLiturgiaDasHorasRoute: typeof OracoesLiturgiaDasHorasRoute
  OracoesNovenasRoute: typeof OracoesNovenasRouteWithChildren
  OracoesRosarioRoute: typeof OracoesRosarioRoute
  OracoesTercoMisericordiaRoute: typeof OracoesTercoMisericordiaRoute
  OracoesViaSacraRoute: typeof OracoesViaSacraRoute
}

const OracoesRouteChildren: OracoesRouteChildren = {
  OracoesLiturgiaDasHorasRoute: OracoesLiturgiaDasHorasRoute,
  OracoesNovenasRoute: OracoesNovenasRouteWithChildren,
  OracoesRosarioRoute: OracoesRosarioRoute,
  OracoesTercoMisericordiaRoute: OracoesTercoMisericordiaRoute,
  OracoesViaSacraRoute: OracoesViaSacraRoute,
}

const OracoesRouteWithChildren =
  OracoesRoute._addFileChildren(OracoesRouteChildren)

interface SantosRouteChildren {
  SantosSlugRoute: typeof SantosSlugRoute
}

const SantosRouteChildren: SantosRouteChildren = {
  SantosSlugRoute: SantosSlugRoute,
}

const SantosRouteWithChildren =
  SantosRoute._addFileChildren(SantosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApologeticaRoute: ApologeticaRoute,
  AssistenteRoute: AssistenteRoute,
  AuthRoute: AuthRoute,
  BibliaRoute: BibliaRouteWithChildren,
  CalendarioLiturgicoRoute: CalendarioLiturgicoRoute,
  CatecismoRoute: CatecismoRouteWithChildren,
  CoroinhasRoute: CoroinhasRoute,
  DoutoresDaIgrejaRoute: DoutoresDaIgrejaRoute,
  FeCatolicaRoute: FeCatolicaRoute,
  MariaRoute: MariaRoute,
  OracoesRoute: OracoesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SacramentosRoute: SacramentosRoute,
  SantosRoute: SantosRouteWithChildren,
  SophiaDiagnosticoRoute: SophiaDiagnosticoRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
