/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapSantosDotxmlRouteImport } from './routes/sitemap-santos[.]xml'
import { Route as SitemapPaginasDotxmlRouteImport } from './routes/sitemap-paginas[.]xml'
import { Route as SitemapNoticiasDotxmlRouteImport } from './routes/sitemap-noticias[.]xml'
import { Route as SitemapBibliaLivrosDotxmlRouteImport } from './routes/sitemap-biblia-livros[.]xml'
import { Route as SitemapBibliaCapitulosDotxmlRouteImport } from './routes/sitemap-biblia-capitulos[.]xml'
import { Route as SantosRouteImport } from './routes/santos'
import { Route as SacramentosRouteImport } from './routes/sacramentos'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as OracoesRouteImport } from './routes/oracoes'
import { Route as MariaRouteImport } from './routes/maria'
import { Route as LiturgiaDiariaRouteImport } from './routes/liturgia-diaria'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as FeCatolicaRouteImport } from './routes/fe-catolica'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as EstudarRouteImport } from './routes/estudar'
import { Route as EmailConfirmadoRouteImport } from './routes/email-confirmado'
import { Route as DoutoresDaIgrejaRouteImport } from './routes/doutores-da-igreja'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as CoroinhasRouteImport } from './routes/coroinhas'
import { Route as CatecismoRouteImport } from './routes/catecismo'
import { Route as CalendarioLiturgicoRouteImport } from './routes/calendario-liturgico'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as BibliaRouteImport } from './routes/biblia'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as ApologeticaRouteImport } from './routes/apologetica'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrilhasIndexRouteImport } from './routes/trilhas.index'
import { Route as SantosIndexRouteImport } from './routes/santos.index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as BibliaIndexRouteImport } from './routes/biblia.index'
import { Route as SantosSlugRouteImport } from './routes/santos.$slug'
import { Route as OracoesViaSacraRouteImport } from './routes/oracoes.via-sacra'
import { Route as OracoesTercoMisericordiaRouteImport } from './routes/oracoes.terco-misericordia'
import { Route as OracoesRosarioRouteImport } from './routes/oracoes.rosario'
import { Route as OracoesNovenasRouteImport } from './routes/oracoes.novenas'
import { Route as OracoesLiturgiaDasHorasRouteImport } from './routes/oracoes.liturgia-das-horas'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as ForumSlugRouteImport } from './routes/forum.$slug'
import { Route as CatecismoParteRouteImport } from './routes/catecismo.$parte'
import { Route as BibliaLeiturasRouteImport } from './routes/biblia.leituras'
import { Route as BibliaLivroRouteImport } from './routes/biblia.$livro'
import { Route as ApiTranscreverRouteImport } from './routes/api/transcrever'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as TrilhasTrilhaIndexRouteImport } from './routes/trilhas.$trilha.index'
import { Route as BibliaLivroIndexRouteImport } from './routes/biblia.$livro.index'
import { Route as TrilhasTrilhaLicaoRouteImport } from './routes/trilhas.$trilha.$licao'
import { Route as OracoesNovenasSlugRouteImport } from './routes/oracoes.novenas.$slug'
import { Route as BibliaLivroCapituloRouteImport } from './routes/biblia.$livro.$capitulo'
import { Route as ApiPublicNoticiasDiariasRouteImport } from './routes/api/public/noticias-diarias'
import { Route as ApiPublicNoticiasRouteImport } from './routes/api/public/noticias'
import { Route as ApiPublicLembretesRouteImport } from './routes/api/public/lembretes'
import { Route as ApiPublicCspReportRouteImport } from './routes/api/public/csp-report'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapSantosDotxmlRoute = SitemapSantosDotxmlRouteImport.update({
  id: '/sitemap-santos.xml',
  path: '/sitemap-santos.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPaginasDotxmlRoute = SitemapPaginasDotxmlRouteImport.update({
  id: '/sitemap-paginas.xml',
  path: '/sitemap-paginas.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapNoticiasDotxmlRoute = SitemapNoticiasDotxmlRouteImport.update({
  id: '/sitemap-noticias.xml',
  path: '/sitemap-noticias.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapBibliaLivrosDotxmlRoute =
  SitemapBibliaLivrosDotxmlRouteImport.update({
    id: '/sitemap-biblia-livros.xml',
    path: '/sitemap-biblia-livros.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapBibliaCapitulosDotxmlRoute =
  SitemapBibliaCapitulosDotxmlRouteImport.update({
    id: '/sitemap-biblia-capitulos.xml',
    path: '/sitemap-biblia-capitulos.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SantosRoute = SantosRouteImport.update({
  id: '/santos',
  path: '/santos',
  getParentRoute: () => rootRouteImport,
} as any)
const SacramentosRoute = SacramentosRouteImport.update({
  id: '/sacramentos',
  path: '/sacramentos',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const OracoesRoute = OracoesRouteImport.update({
  id: '/oracoes',
  path: '/oracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MariaRoute = MariaRouteImport.update({
  id: '/maria',
  path: '/maria',
  getParentRoute: () => rootRouteImport,
} as any)
const LiturgiaDiariaRoute = LiturgiaDiariaRouteImport.update({
  id: '/liturgia-diaria',
  path: '/liturgia-diaria',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const FeCatolicaRoute = FeCatolicaRouteImport.update({
  id: '/fe-catolica',
  path: '/fe-catolica',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudarRoute = EstudarRouteImport.update({
  id: '/estudar',
  path: '/estudar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailConfirmadoRoute = EmailConfirmadoRouteImport.update({
  id: '/email-confirmado',
  path: '/email-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const DoutoresDaIgrejaRoute = DoutoresDaIgrejaRouteImport.update({
  id: '/doutores-da-igreja',
  path: '/doutores-da-igreja',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const CoroinhasRoute = CoroinhasRouteImport.update({
  id: '/coroinhas',
  path: '/coroinhas',
  getParentRoute: () => rootRouteImport,
} as any)
const CatecismoRoute = CatecismoRouteImport.update({
  id: '/catecismo',
  path: '/catecismo',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioLiturgicoRoute = CalendarioLiturgicoRouteImport.update({
  id: '/calendario-liturgico',
  path: '/calendario-liturgico',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaRoute = BibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const ApologeticaRoute = ApologeticaRouteImport.update({
  id: '/apologetica',
  path: '/apologetica',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhasIndexRoute = TrilhasIndexRouteImport.update({
  id: '/trilhas/',
  path: '/trilhas/',
  getParentRoute: () => rootRouteImport,
} as any)
const SantosIndexRoute = SantosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SantosRoute,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaIndexRoute = BibliaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliaRoute,
} as any)
const SantosSlugRoute = SantosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SantosRoute,
} as any)
const OracoesViaSacraRoute = OracoesViaSacraRouteImport.update({
  id: '/via-sacra',
  path: '/via-sacra',
  getParentRoute: () => OracoesRoute,
} as any)
const OracoesTercoMisericordiaRoute =
  OracoesTercoMisericordiaRouteImport.update({
    id: '/terco-misericordia',
    path: '/terco-misericordia',
    getParentRoute: () => OracoesRoute,
  } as any)
const OracoesRosarioRoute = OracoesRosarioRouteImport.update({
  id: '/rosario',
  path: '/rosario',
  getParentRoute: () => OracoesRoute,
} as any)
const OracoesNovenasRoute = OracoesNovenasRouteImport.update({
  id: '/novenas',
  path: '/novenas',
  getParentRoute: () => OracoesRoute,
} as any)
const OracoesLiturgiaDasHorasRoute = OracoesLiturgiaDasHorasRouteImport.update({
  id: '/liturgia-das-horas',
  path: '/liturgia-das-horas',
  getParentRoute: () => OracoesRoute,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumSlugRoute = ForumSlugRouteImport.update({
  id: '/forum/$slug',
  path: '/forum/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CatecismoParteRoute = CatecismoParteRouteImport.update({
  id: '/$parte',
  path: '/$parte',
  getParentRoute: () => CatecismoRoute,
} as any)
const BibliaLeiturasRoute = BibliaLeiturasRouteImport.update({
  id: '/leituras',
  path: '/leituras',
  getParentRoute: () => BibliaRoute,
} as any)
const BibliaLivroRoute = BibliaLivroRouteImport.update({
  id: '/$livro',
  path: '/$livro',
  getParentRoute: () => BibliaRoute,
} as any)
const ApiTranscreverRoute = ApiTranscreverRouteImport.update({
  id: '/api/transcrever',
  path: '/api/transcrever',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhasTrilhaIndexRoute = TrilhasTrilhaIndexRouteImport.update({
  id: '/trilhas/$trilha/',
  path: '/trilhas/$trilha/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaLivroIndexRoute = BibliaLivroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliaLivroRoute,
} as any)
const TrilhasTrilhaLicaoRoute = TrilhasTrilhaLicaoRouteImport.update({
  id: '/trilhas/$trilha/$licao',
  path: '/trilhas/$trilha/$licao',
  getParentRoute: () => rootRouteImport,
} as any)
const OracoesNovenasSlugRoute = OracoesNovenasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OracoesNovenasRoute,
} as any)
const BibliaLivroCapituloRoute = BibliaLivroCapituloRouteImport.update({
  id: '/$capitulo',
  path: '/$capitulo',
  getParentRoute: () => BibliaLivroRoute,
} as any)
const ApiPublicNoticiasDiariasRoute =
  ApiPublicNoticiasDiariasRouteImport.update({
    id: '/api/public/noticias-diarias',
    path: '/api/public/noticias-diarias',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNoticiasRoute = ApiPublicNoticiasRouteImport.update({
  id: '/api/public/noticias',
  path: '/api/public/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLembretesRoute = ApiPublicLembretesRouteImport.update({
  id: '/api/public/lembretes',
  path: '/api/public/lembretes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCspReportRoute = ApiPublicCspReportRouteImport.update({
  id: '/api/public/csp-report',
  path: '/api/public/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apologetica': typeof ApologeticaRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/biblia': typeof BibliaRouteWithChildren
  '/busca': typeof BuscaRoute
  '/calendario-liturgico': typeof CalendarioLiturgicoRoute
  '/catecismo': typeof CatecismoRouteWithChildren
  '/coroinhas': typeof CoroinhasRoute
  '/design-system': typeof DesignSystemRoute
  '/doutores-da-igreja': typeof DoutoresDaIgrejaRoute
  '/email-confirmado': typeof EmailConfirmadoRoute
  '/estudar': typeof EstudarRoute
  '/explorar': typeof ExplorarRoute
  '/favoritos': typeof FavoritosRoute
  '/fe-catolica': typeof FeCatolicaRoute
  '/fontes': typeof FontesRoute
  '/glossario': typeof GlossarioRoute
  '/liturgia-diaria': typeof LiturgiaDiariaRoute
  '/maria': typeof MariaRoute
  '/oracoes': typeof OracoesRouteWithChildren
  '/painel': typeof PainelRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sacramentos': typeof SacramentosRoute
  '/santos': typeof SantosRouteWithChildren
  '/sitemap-biblia-capitulos.xml': typeof SitemapBibliaCapitulosDotxmlRoute
  '/sitemap-biblia-livros.xml': typeof SitemapBibliaLivrosDotxmlRoute
  '/sitemap-noticias.xml': typeof SitemapNoticiasDotxmlRoute
  '/sitemap-paginas.xml': typeof SitemapPaginasDotxmlRoute
  '/sitemap-santos.xml': typeof SitemapSantosDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcrever': typeof ApiTranscreverRoute
  '/biblia/$livro': typeof BibliaLivroRouteWithChildren
  '/biblia/leituras': typeof BibliaLeiturasRoute
  '/catecismo/$parte': typeof CatecismoParteRoute
  '/forum/$slug': typeof ForumSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/oracoes/liturgia-das-horas': typeof OracoesLiturgiaDasHorasRoute
  '/oracoes/novenas': typeof OracoesNovenasRouteWithChildren
  '/oracoes/rosario': typeof OracoesRosarioRoute
  '/oracoes/terco-misericordia': typeof OracoesTercoMisericordiaRoute
  '/oracoes/via-sacra': typeof OracoesViaSacraRoute
  '/santos/$slug': typeof SantosSlugRoute
  '/biblia/': typeof BibliaIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/santos/': typeof SantosIndexRoute
  '/trilhas/': typeof TrilhasIndexRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/lembretes': typeof ApiPublicLembretesRoute
  '/api/public/noticias': typeof ApiPublicNoticiasRoute
  '/api/public/noticias-diarias': typeof ApiPublicNoticiasDiariasRoute
  '/biblia/$livro/$capitulo': typeof BibliaLivroCapituloRoute
  '/oracoes/novenas/$slug': typeof OracoesNovenasSlugRoute
  '/trilhas/$trilha/$licao': typeof TrilhasTrilhaLicaoRoute
  '/biblia/$livro/': typeof BibliaLivroIndexRoute
  '/trilhas/$trilha/': typeof TrilhasTrilhaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apologetica': typeof ApologeticaRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/calendario-liturgico': typeof CalendarioLiturgicoRoute
  '/catecismo': typeof CatecismoRouteWithChildren
  '/coroinhas': typeof CoroinhasRoute
  '/design-system': typeof DesignSystemRoute
  '/doutores-da-igreja': typeof DoutoresDaIgrejaRoute
  '/email-confirmado': typeof EmailConfirmadoRoute
  '/estudar': typeof EstudarRoute
  '/explorar': typeof ExplorarRoute
  '/favoritos': typeof FavoritosRoute
  '/fe-catolica': typeof FeCatolicaRoute
  '/fontes': typeof FontesRoute
  '/glossario': typeof GlossarioRoute
  '/liturgia-diaria': typeof LiturgiaDiariaRoute
  '/maria': typeof MariaRoute
  '/oracoes': typeof OracoesRouteWithChildren
  '/painel': typeof PainelRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sacramentos': typeof SacramentosRoute
  '/sitemap-biblia-capitulos.xml': typeof SitemapBibliaCapitulosDotxmlRoute
  '/sitemap-biblia-livros.xml': typeof SitemapBibliaLivrosDotxmlRoute
  '/sitemap-noticias.xml': typeof SitemapNoticiasDotxmlRoute
  '/sitemap-paginas.xml': typeof SitemapPaginasDotxmlRoute
  '/sitemap-santos.xml': typeof SitemapSantosDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcrever': typeof ApiTranscreverRoute
  '/biblia/leituras': typeof BibliaLeiturasRoute
  '/catecismo/$parte': typeof CatecismoParteRoute
  '/forum/$slug': typeof ForumSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/oracoes/liturgia-das-horas': typeof OracoesLiturgiaDasHorasRoute
  '/oracoes/novenas': typeof OracoesNovenasRouteWithChildren
  '/oracoes/rosario': typeof OracoesRosarioRoute
  '/oracoes/terco-misericordia': typeof OracoesTercoMisericordiaRoute
  '/oracoes/via-sacra': typeof OracoesViaSacraRoute
  '/santos/$slug': typeof SantosSlugRoute
  '/biblia': typeof BibliaIndexRoute
  '/forum': typeof ForumIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/santos': typeof SantosIndexRoute
  '/trilhas': typeof TrilhasIndexRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/lembretes': typeof ApiPublicLembretesRoute
  '/api/public/noticias': typeof ApiPublicNoticiasRoute
  '/api/public/noticias-diarias': typeof ApiPublicNoticiasDiariasRoute
  '/biblia/$livro/$capitulo': typeof BibliaLivroCapituloRoute
  '/oracoes/novenas/$slug': typeof OracoesNovenasSlugRoute
  '/trilhas/$trilha/$licao': typeof TrilhasTrilhaLicaoRoute
  '/biblia/$livro': typeof BibliaLivroIndexRoute
  '/trilhas/$trilha': typeof TrilhasTrilhaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apologetica': typeof ApologeticaRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/biblia': typeof BibliaRouteWithChildren
  '/busca': typeof BuscaRoute
  '/calendario-liturgico': typeof CalendarioLiturgicoRoute
  '/catecismo': typeof CatecismoRouteWithChildren
  '/coroinhas': typeof CoroinhasRoute
  '/design-system': typeof DesignSystemRoute
  '/doutores-da-igreja': typeof DoutoresDaIgrejaRoute
  '/email-confirmado': typeof EmailConfirmadoRoute
  '/estudar': typeof EstudarRoute
  '/explorar': typeof ExplorarRoute
  '/favoritos': typeof FavoritosRoute
  '/fe-catolica': typeof FeCatolicaRoute
  '/fontes': typeof FontesRoute
  '/glossario': typeof GlossarioRoute
  '/liturgia-diaria': typeof LiturgiaDiariaRoute
  '/maria': typeof MariaRoute
  '/oracoes': typeof OracoesRouteWithChildren
  '/painel': typeof PainelRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sacramentos': typeof SacramentosRoute
  '/santos': typeof SantosRouteWithChildren
  '/sitemap-biblia-capitulos.xml': typeof SitemapBibliaCapitulosDotxmlRoute
  '/sitemap-biblia-livros.xml': typeof SitemapBibliaLivrosDotxmlRoute
  '/sitemap-noticias.xml': typeof SitemapNoticiasDotxmlRoute
  '/sitemap-paginas.xml': typeof SitemapPaginasDotxmlRoute
  '/sitemap-santos.xml': typeof SitemapSantosDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcrever': typeof ApiTranscreverRoute
  '/biblia/$livro': typeof BibliaLivroRouteWithChildren
  '/biblia/leituras': typeof BibliaLeiturasRoute
  '/catecismo/$parte': typeof CatecismoParteRoute
  '/forum/$slug': typeof ForumSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/oracoes/liturgia-das-horas': typeof OracoesLiturgiaDasHorasRoute
  '/oracoes/novenas': typeof OracoesNovenasRouteWithChildren
  '/oracoes/rosario': typeof OracoesRosarioRoute
  '/oracoes/terco-misericordia': typeof OracoesTercoMisericordiaRoute
  '/oracoes/via-sacra': typeof OracoesViaSacraRoute
  '/santos/$slug': typeof SantosSlugRoute
  '/biblia/': typeof BibliaIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/santos/': typeof SantosIndexRoute
  '/trilhas/': typeof TrilhasIndexRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/lembretes': typeof ApiPublicLembretesRoute
  '/api/public/noticias': typeof ApiPublicNoticiasRoute
  '/api/public/noticias-diarias': typeof ApiPublicNoticiasDiariasRoute
  '/biblia/$livro/$capitulo': typeof BibliaLivroCapituloRoute
  '/oracoes/novenas/$slug': typeof OracoesNovenasSlugRoute
  '/trilhas/$trilha/$licao': typeof TrilhasTrilhaLicaoRoute
  '/biblia/$livro/': typeof BibliaLivroIndexRoute
  '/trilhas/$trilha/': typeof TrilhasTrilhaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apologetica'
    | '/assistente'
    | '/auth'
    | '/biblia'
    | '/busca'
    | '/calendario-liturgico'
    | '/catecismo'
    | '/coroinhas'
    | '/design-system'
    | '/doutores-da-igreja'
    | '/email-confirmado'
    | '/estudar'
    | '/explorar'
    | '/favoritos'
    | '/fe-catolica'
    | '/fontes'
    | '/glossario'
    | '/liturgia-diaria'
    | '/maria'
    | '/oracoes'
    | '/painel'
    | '/privacidade'
    | '/redefinir-senha'
    | '/sacramentos'
    | '/santos'
    | '/sitemap-biblia-capitulos.xml'
    | '/sitemap-biblia-livros.xml'
    | '/sitemap-noticias.xml'
    | '/sitemap-paginas.xml'
    | '/sitemap-santos.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/api/chat'
    | '/api/transcrever'
    | '/biblia/$livro'
    | '/biblia/leituras'
    | '/catecismo/$parte'
    | '/forum/$slug'
    | '/noticias/$slug'
    | '/oracoes/liturgia-das-horas'
    | '/oracoes/novenas'
    | '/oracoes/rosario'
    | '/oracoes/terco-misericordia'
    | '/oracoes/via-sacra'
    | '/santos/$slug'
    | '/biblia/'
    | '/forum/'
    | '/noticias/'
    | '/santos/'
    | '/trilhas/'
    | '/api/public/csp-report'
    | '/api/public/lembretes'
    | '/api/public/noticias'
    | '/api/public/noticias-diarias'
    | '/biblia/$livro/$capitulo'
    | '/oracoes/novenas/$slug'
    | '/trilhas/$trilha/$licao'
    | '/biblia/$livro/'
    | '/trilhas/$trilha/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apologetica'
    | '/assistente'
    | '/auth'
    | '/busca'
    | '/calendario-liturgico'
    | '/catecismo'
    | '/coroinhas'
    | '/design-system'
    | '/doutores-da-igreja'
    | '/email-confirmado'
    | '/estudar'
    | '/explorar'
    | '/favoritos'
    | '/fe-catolica'
    | '/fontes'
    | '/glossario'
    | '/liturgia-diaria'
    | '/maria'
    | '/oracoes'
    | '/painel'
    | '/privacidade'
    | '/redefinir-senha'
    | '/sacramentos'
    | '/sitemap-biblia-capitulos.xml'
    | '/sitemap-biblia-livros.xml'
    | '/sitemap-noticias.xml'
    | '/sitemap-paginas.xml'
    | '/sitemap-santos.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/api/chat'
    | '/api/transcrever'
    | '/biblia/leituras'
    | '/catecismo/$parte'
    | '/forum/$slug'
    | '/noticias/$slug'
    | '/oracoes/liturgia-das-horas'
    | '/oracoes/novenas'
    | '/oracoes/rosario'
    | '/oracoes/terco-misericordia'
    | '/oracoes/via-sacra'
    | '/santos/$slug'
    | '/biblia'
    | '/forum'
    | '/noticias'
    | '/santos'
    | '/trilhas'
    | '/api/public/csp-report'
    | '/api/public/lembretes'
    | '/api/public/noticias'
    | '/api/public/noticias-diarias'
    | '/biblia/$livro/$capitulo'
    | '/oracoes/novenas/$slug'
    | '/trilhas/$trilha/$licao'
    | '/biblia/$livro'
    | '/trilhas/$trilha'
  id:
    | '__root__'
    | '/'
    | '/apologetica'
    | '/assistente'
    | '/auth'
    | '/biblia'
    | '/busca'
    | '/calendario-liturgico'
    | '/catecismo'
    | '/coroinhas'
    | '/design-system'
    | '/doutores-da-igreja'
    | '/email-confirmado'
    | '/estudar'
    | '/explorar'
    | '/favoritos'
    | '/fe-catolica'
    | '/fontes'
    | '/glossario'
    | '/liturgia-diaria'
    | '/maria'
    | '/oracoes'
    | '/painel'
    | '/privacidade'
    | '/redefinir-senha'
    | '/sacramentos'
    | '/santos'
    | '/sitemap-biblia-capitulos.xml'
    | '/sitemap-biblia-livros.xml'
    | '/sitemap-noticias.xml'
    | '/sitemap-paginas.xml'
    | '/sitemap-santos.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/api/chat'
    | '/api/transcrever'
    | '/biblia/$livro'
    | '/biblia/leituras'
    | '/catecismo/$parte'
    | '/forum/$slug'
    | '/noticias/$slug'
    | '/oracoes/liturgia-das-horas'
    | '/oracoes/novenas'
    | '/oracoes/rosario'
    | '/oracoes/terco-misericordia'
    | '/oracoes/via-sacra'
    | '/santos/$slug'
    | '/biblia/'
    | '/forum/'
    | '/noticias/'
    | '/santos/'
    | '/trilhas/'
    | '/api/public/csp-report'
    | '/api/public/lembretes'
    | '/api/public/noticias'
    | '/api/public/noticias-diarias'
    | '/biblia/$livro/$capitulo'
    | '/oracoes/novenas/$slug'
    | '/trilhas/$trilha/$licao'
    | '/biblia/$livro/'
    | '/trilhas/$trilha/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApologeticaRoute: typeof ApologeticaRoute
  AssistenteRoute: typeof AssistenteRoute
  AuthRoute: typeof AuthRoute
  BibliaRoute: typeof BibliaRouteWithChildren
  BuscaRoute: typeof BuscaRoute
  CalendarioLiturgicoRoute: typeof CalendarioLiturgicoRoute
  CatecismoRoute: typeof CatecismoRouteWithChildren
  CoroinhasRoute: typeof CoroinhasRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DoutoresDaIgrejaRoute: typeof DoutoresDaIgrejaRoute
  EmailConfirmadoRoute: typeof EmailConfirmadoRoute
  EstudarRoute: typeof EstudarRoute
  ExplorarRoute: typeof ExplorarRoute
  FavoritosRoute: typeof FavoritosRoute
  FeCatolicaRoute: typeof FeCatolicaRoute
  FontesRoute: typeof FontesRoute
  GlossarioRoute: typeof GlossarioRoute
  LiturgiaDiariaRoute: typeof LiturgiaDiariaRoute
  MariaRoute: typeof MariaRoute
  OracoesRoute: typeof OracoesRouteWithChildren
  PainelRoute: typeof PainelRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SacramentosRoute: typeof SacramentosRoute
  SantosRoute: typeof SantosRouteWithChildren
  SitemapBibliaCapitulosDotxmlRoute: typeof SitemapBibliaCapitulosDotxmlRoute
  SitemapBibliaLivrosDotxmlRoute: typeof SitemapBibliaLivrosDotxmlRoute
  SitemapNoticiasDotxmlRoute: typeof SitemapNoticiasDotxmlRoute
  SitemapPaginasDotxmlRoute: typeof SitemapPaginasDotxmlRoute
  SitemapSantosDotxmlRoute: typeof SitemapSantosDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTranscreverRoute: typeof ApiTranscreverRoute
  ForumSlugRoute: typeof ForumSlugRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  ForumIndexRoute: typeof ForumIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  TrilhasIndexRoute: typeof TrilhasIndexRoute
  ApiPublicCspReportRoute: typeof ApiPublicCspReportRoute
  ApiPublicLembretesRoute: typeof ApiPublicLembretesRoute
  ApiPublicNoticiasRoute: typeof ApiPublicNoticiasRoute
  ApiPublicNoticiasDiariasRoute: typeof ApiPublicNoticiasDiariasRoute
  TrilhasTrilhaLicaoRoute: typeof TrilhasTrilhaLicaoRoute
  TrilhasTrilhaIndexRoute: typeof TrilhasTrilhaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-santos.xml': {
      id: '/sitemap-santos.xml'
      path: '/sitemap-santos.xml'
      fullPath: '/sitemap-santos.xml'
      preLoaderRoute: typeof SitemapSantosDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-paginas.xml': {
      id: '/sitemap-paginas.xml'
      path: '/sitemap-paginas.xml'
      fullPath: '/sitemap-paginas.xml'
      preLoaderRoute: typeof SitemapPaginasDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-noticias.xml': {
      id: '/sitemap-noticias.xml'
      path: '/sitemap-noticias.xml'
      fullPath: '/sitemap-noticias.xml'
      preLoaderRoute: typeof SitemapNoticiasDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-biblia-livros.xml': {
      id: '/sitemap-biblia-livros.xml'
      path: '/sitemap-biblia-livros.xml'
      fullPath: '/sitemap-biblia-livros.xml'
      preLoaderRoute: typeof SitemapBibliaLivrosDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-biblia-capitulos.xml': {
      id: '/sitemap-biblia-capitulos.xml'
      path: '/sitemap-biblia-capitulos.xml'
      fullPath: '/sitemap-biblia-capitulos.xml'
      preLoaderRoute: typeof SitemapBibliaCapitulosDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santos': {
      id: '/santos'
      path: '/santos'
      fullPath: '/santos'
      preLoaderRoute: typeof SantosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sacramentos': {
      id: '/sacramentos'
      path: '/sacramentos'
      fullPath: '/sacramentos'
      preLoaderRoute: typeof SacramentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracoes': {
      id: '/oracoes'
      path: '/oracoes'
      fullPath: '/oracoes'
      preLoaderRoute: typeof OracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maria': {
      id: '/maria'
      path: '/maria'
      fullPath: '/maria'
      preLoaderRoute: typeof MariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liturgia-diaria': {
      id: '/liturgia-diaria'
      path: '/liturgia-diaria'
      fullPath: '/liturgia-diaria'
      preLoaderRoute: typeof LiturgiaDiariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fe-catolica': {
      id: '/fe-catolica'
      path: '/fe-catolica'
      fullPath: '/fe-catolica'
      preLoaderRoute: typeof FeCatolicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudar': {
      id: '/estudar'
      path: '/estudar'
      fullPath: '/estudar'
      preLoaderRoute: typeof EstudarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-confirmado': {
      id: '/email-confirmado'
      path: '/email-confirmado'
      fullPath: '/email-confirmado'
      preLoaderRoute: typeof EmailConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doutores-da-igreja': {
      id: '/doutores-da-igreja'
      path: '/doutores-da-igreja'
      fullPath: '/doutores-da-igreja'
      preLoaderRoute: typeof DoutoresDaIgrejaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coroinhas': {
      id: '/coroinhas'
      path: '/coroinhas'
      fullPath: '/coroinhas'
      preLoaderRoute: typeof CoroinhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catecismo': {
      id: '/catecismo'
      path: '/catecismo'
      fullPath: '/catecismo'
      preLoaderRoute: typeof CatecismoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario-liturgico': {
      id: '/calendario-liturgico'
      path: '/calendario-liturgico'
      fullPath: '/calendario-liturgico'
      preLoaderRoute: typeof CalendarioLiturgicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia': {
      id: '/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof BibliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apologetica': {
      id: '/apologetica'
      path: '/apologetica'
      fullPath: '/apologetica'
      preLoaderRoute: typeof ApologeticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas/': {
      id: '/trilhas/'
      path: '/trilhas'
      fullPath: '/trilhas/'
      preLoaderRoute: typeof TrilhasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santos/': {
      id: '/santos/'
      path: '/'
      fullPath: '/santos/'
      preLoaderRoute: typeof SantosIndexRouteImport
      parentRoute: typeof SantosRoute
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia/': {
      id: '/biblia/'
      path: '/'
      fullPath: '/biblia/'
      preLoaderRoute: typeof BibliaIndexRouteImport
      parentRoute: typeof BibliaRoute
    }
    '/santos/$slug': {
      id: '/santos/$slug'
      path: '/$slug'
      fullPath: '/santos/$slug'
      preLoaderRoute: typeof SantosSlugRouteImport
      parentRoute: typeof SantosRoute
    }
    '/oracoes/via-sacra': {
      id: '/oracoes/via-sacra'
      path: '/via-sacra'
      fullPath: '/oracoes/via-sacra'
      preLoaderRoute: typeof OracoesViaSacraRouteImport
      parentRoute: typeof OracoesRoute
    }
    '/oracoes/terco-misericordia': {
      id: '/oracoes/terco-misericordia'
      path: '/terco-misericordia'
      fullPath: '/oracoes/terco-misericordia'
      preLoaderRoute: typeof OracoesTercoMisericordiaRouteImport
      parentRoute: typeof OracoesRoute
    }
    '/oracoes/rosario': {
      id: '/oracoes/rosario'
      path: '/rosario'
      fullPath: '/oracoes/rosario'
      preLoaderRoute: typeof OracoesRosarioRouteImport
      parentRoute: typeof OracoesRoute
    }
    '/oracoes/novenas': {
      id: '/oracoes/novenas'
      path: '/novenas'
      fullPath: '/oracoes/novenas'
      preLoaderRoute: typeof OracoesNovenasRouteImport
      parentRoute: typeof OracoesRoute
    }
    '/oracoes/liturgia-das-horas': {
      id: '/oracoes/liturgia-das-horas'
      path: '/liturgia-das-horas'
      fullPath: '/oracoes/liturgia-das-horas'
      preLoaderRoute: typeof OracoesLiturgiaDasHorasRouteImport
      parentRoute: typeof OracoesRoute
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$slug': {
      id: '/forum/$slug'
      path: '/forum/$slug'
      fullPath: '/forum/$slug'
      preLoaderRoute: typeof ForumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catecismo/$parte': {
      id: '/catecismo/$parte'
      path: '/$parte'
      fullPath: '/catecismo/$parte'
      preLoaderRoute: typeof CatecismoParteRouteImport
      parentRoute: typeof CatecismoRoute
    }
    '/biblia/leituras': {
      id: '/biblia/leituras'
      path: '/leituras'
      fullPath: '/biblia/leituras'
      preLoaderRoute: typeof BibliaLeiturasRouteImport
      parentRoute: typeof BibliaRoute
    }
    '/biblia/$livro': {
      id: '/biblia/$livro'
      path: '/$livro'
      fullPath: '/biblia/$livro'
      preLoaderRoute: typeof BibliaLivroRouteImport
      parentRoute: typeof BibliaRoute
    }
    '/api/transcrever': {
      id: '/api/transcrever'
      path: '/api/transcrever'
      fullPath: '/api/transcrever'
      preLoaderRoute: typeof ApiTranscreverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas/$trilha/': {
      id: '/trilhas/$trilha/'
      path: '/trilhas/$trilha'
      fullPath: '/trilhas/$trilha/'
      preLoaderRoute: typeof TrilhasTrilhaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia/$livro/': {
      id: '/biblia/$livro/'
      path: '/'
      fullPath: '/biblia/$livro/'
      preLoaderRoute: typeof BibliaLivroIndexRouteImport
      parentRoute: typeof BibliaLivroRoute
    }
    '/trilhas/$trilha/$licao': {
      id: '/trilhas/$trilha/$licao'
      path: '/trilhas/$trilha/$licao'
      fullPath: '/trilhas/$trilha/$licao'
      preLoaderRoute: typeof TrilhasTrilhaLicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracoes/novenas/$slug': {
      id: '/oracoes/novenas/$slug'
      path: '/$slug'
      fullPath: '/oracoes/novenas/$slug'
      preLoaderRoute: typeof OracoesNovenasSlugRouteImport
      parentRoute: typeof OracoesNovenasRoute
    }
    '/biblia/$livro/$capitulo': {
      id: '/biblia/$livro/$capitulo'
      path: '/$capitulo'
      fullPath: '/biblia/$livro/$capitulo'
      preLoaderRoute: typeof BibliaLivroCapituloRouteImport
      parentRoute: typeof BibliaLivroRoute
    }
    '/api/public/noticias-diarias': {
      id: '/api/public/noticias-diarias'
      path: '/api/public/noticias-diarias'
      fullPath: '/api/public/noticias-diarias'
      preLoaderRoute: typeof ApiPublicNoticiasDiariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/noticias': {
      id: '/api/public/noticias'
      path: '/api/public/noticias'
      fullPath: '/api/public/noticias'
      preLoaderRoute: typeof ApiPublicNoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lembretes': {
      id: '/api/public/lembretes'
      path: '/api/public/lembretes'
      fullPath: '/api/public/lembretes'
      preLoaderRoute: typeof ApiPublicLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/csp-report': {
      id: '/api/public/csp-report'
      path: '/api/public/csp-report'
      fullPath: '/api/public/csp-report'
      preLoaderRoute: typeof ApiPublicCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BibliaLivroRouteChildren {
  BibliaLivroCapituloRoute: typeof BibliaLivroCapituloRoute
  BibliaLivroIndexRoute: typeof BibliaLivroIndexRoute
}

const BibliaLivroRouteChildren: BibliaLivroRouteChildren = {
  BibliaLivroCapituloRoute: BibliaLivroCapituloRoute,
  BibliaLivroIndexRoute: BibliaLivroIndexRoute,
}

const BibliaLivroRouteWithChildren = BibliaLivroRoute._addFileChildren(
  BibliaLivroRouteChildren,
)

interface BibliaRouteChildren {
  BibliaLivroRoute: typeof BibliaLivroRouteWithChildren
  BibliaLeiturasRoute: typeof BibliaLeiturasRoute
  BibliaIndexRoute: typeof BibliaIndexRoute
}

const BibliaRouteChildren: BibliaRouteChildren = {
  BibliaLivroRoute: BibliaLivroRouteWithChildren,
  BibliaLeiturasRoute: BibliaLeiturasRoute,
  BibliaIndexRoute: BibliaIndexRoute,
}

const BibliaRouteWithChildren =
  BibliaRoute._addFileChildren(BibliaRouteChildren)

interface CatecismoRouteChildren {
  CatecismoParteRoute: typeof CatecismoParteRoute
}

const CatecismoRouteChildren: CatecismoRouteChildren = {
  CatecismoParteRoute: CatecismoParteRoute,
}

const CatecismoRouteWithChildren = CatecismoRoute._addFileChildren(
  CatecismoRouteChildren,
)

interface OracoesNovenasRouteChildren {
  OracoesNovenasSlugRoute: typeof OracoesNovenasSlugRoute
}

const OracoesNovenasRouteChildren: OracoesNovenasRouteChildren = {
  OracoesNovenasSlugRoute: OracoesNovenasSlugRoute,
}

const OracoesNovenasRouteWithChildren = OracoesNovenasRoute._addFileChildren(
  OracoesNovenasRouteChildren,
)

interface OracoesRouteChildren {
  OracoesLiturgiaDasHorasRoute: typeof OracoesLiturgiaDasHorasRoute
  OracoesNovenasRoute: typeof OracoesNovenasRouteWithChildren
  OracoesRosarioRoute: typeof OracoesRosarioRoute
  OracoesTercoMisericordiaRoute: typeof OracoesTercoMisericordiaRoute
  OracoesViaSacraRoute: typeof OracoesViaSacraRoute
}

const OracoesRouteChildren: OracoesRouteChildren = {
  OracoesLiturgiaDasHorasRoute: OracoesLiturgiaDasHorasRoute,
  OracoesNovenasRoute: OracoesNovenasRouteWithChildren,
  OracoesRosarioRoute: OracoesRosarioRoute,
  OracoesTercoMisericordiaRoute: OracoesTercoMisericordiaRoute,
  OracoesViaSacraRoute: OracoesViaSacraRoute,
}

const OracoesRouteWithChildren =
  OracoesRoute._addFileChildren(OracoesRouteChildren)

interface SantosRouteChildren {
  SantosSlugRoute: typeof SantosSlugRoute
  SantosIndexRoute: typeof SantosIndexRoute
}

const SantosRouteChildren: SantosRouteChildren = {
  SantosSlugRoute: SantosSlugRoute,
  SantosIndexRoute: SantosIndexRoute,
}

const SantosRouteWithChildren =
  SantosRoute._addFileChildren(SantosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApologeticaRoute: ApologeticaRoute,
  AssistenteRoute: AssistenteRoute,
  AuthRoute: AuthRoute,
  BibliaRoute: BibliaRouteWithChildren,
  BuscaRoute: BuscaRoute,
  CalendarioLiturgicoRoute: CalendarioLiturgicoRoute,
  CatecismoRoute: CatecismoRouteWithChildren,
  CoroinhasRoute: CoroinhasRoute,
  DesignSystemRoute: DesignSystemRoute,
  DoutoresDaIgrejaRoute: DoutoresDaIgrejaRoute,
  EmailConfirmadoRoute: EmailConfirmadoRoute,
  EstudarRoute: EstudarRoute,
  ExplorarRoute: ExplorarRoute,
  FavoritosRoute: FavoritosRoute,
  FeCatolicaRoute: FeCatolicaRoute,
  FontesRoute: FontesRoute,
  GlossarioRoute: GlossarioRoute,
  LiturgiaDiariaRoute: LiturgiaDiariaRoute,
  MariaRoute: MariaRoute,
  OracoesRoute: OracoesRouteWithChildren,
  PainelRoute: PainelRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SacramentosRoute: SacramentosRoute,
  SantosRoute: SantosRouteWithChildren,
  SitemapBibliaCapitulosDotxmlRoute: SitemapBibliaCapitulosDotxmlRoute,
  SitemapBibliaLivrosDotxmlRoute: SitemapBibliaLivrosDotxmlRoute,
  SitemapNoticiasDotxmlRoute: SitemapNoticiasDotxmlRoute,
  SitemapPaginasDotxmlRoute: SitemapPaginasDotxmlRoute,
  SitemapSantosDotxmlRoute: SitemapSantosDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTranscreverRoute: ApiTranscreverRoute,
  ForumSlugRoute: ForumSlugRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  ForumIndexRoute: ForumIndexRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  TrilhasIndexRoute: TrilhasIndexRoute,
  ApiPublicCspReportRoute: ApiPublicCspReportRoute,
  ApiPublicLembretesRoute: ApiPublicLembretesRoute,
  ApiPublicNoticiasRoute: ApiPublicNoticiasRoute,
  ApiPublicNoticiasDiariasRoute: ApiPublicNoticiasDiariasRoute,
  TrilhasTrilhaLicaoRoute: TrilhasTrilhaLicaoRoute,
  TrilhasTrilhaIndexRoute: TrilhasTrilhaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
