INSERT INTO public.conquistas_catalogo (slug, titulo, descricao, icone, xp) VALUES
  ('streak-14', 'Quinzena Fiel', 'Quatorze dias consecutivos de oração.', 'flame', 120),
  ('streak-60', 'Dois Meses de Fogo', 'Sessenta dias consecutivos de oração.', 'flame', 400),
  ('streak-365', 'Ano Litúrgico', 'Um ano inteiro de oração sem interrupção.', 'crown', 1500),
  ('oracoes-10', 'Dez Amém', 'Registrou dez dias de oração no diário.', 'sparkles', 60),
  ('oracoes-50', 'Alma Orante', 'Registrou cinquenta dias de oração no diário.', 'sparkles', 220),
  ('oracoes-100', 'Cem Colóquios', 'Registrou cem dias de oração no diário.', 'award', 500),
  ('oracao-30min', 'Meia Hora com Deus', 'Rezou por trinta minutos num só dia.', 'clock', 40),
  ('vigilia', 'Vigília', 'Rezou por uma hora ou mais num só dia.', 'moon', 120),
  ('reflexao-profunda', 'Coração Aberto', 'Escreveu uma reflexão longa e sincera no diário.', 'pen-line', 30),
  ('capitulos-25', 'Peregrino da Palavra', 'Leu vinte e cinco capítulos da Bíblia.', 'book-open', 120),
  ('capitulos-50', 'Cinquenta Colunas', 'Leu cinquenta capítulos da Bíblia.', 'book-open', 250),
  ('capitulos-100', 'Centúria Bíblica', 'Leu cem capítulos da Bíblia.', 'book-open', 500),
  ('capitulos-250', 'Biblioteca Viva', 'Leu duzentos e cinquenta capítulos da Bíblia.', 'library', 1200),
  ('livro-completo', 'Livro Concluído', 'Terminou um livro inteiro da Bíblia.', 'scroll', 150),
  ('cinco-livros', 'Cinco Livros', 'Concluiu cinco livros da Bíblia.', 'scroll', 400),
  ('pentateuco', 'Torá Percorrida', 'Concluiu os cinco livros do Pentateuco.', 'mountain', 700),
  ('quatro-evangelhos', 'Os Quatro Evangelhos', 'Concluiu Mateus, Marcos, Lucas e João.', 'mountain', 900),
  ('salterio', 'Saltério', 'Concluiu o livro dos Salmos.', 'music', 800),
  ('novo-testamento', 'Novo Testamento', 'Concluiu todos os livros do Novo Testamento.', 'crown', 2000),
  ('favoritos-10', 'Tesouro de Versículos', 'Guardou dez versículos favoritos.', 'bookmark', 60),
  ('favoritos-50', 'Antologia Sagrada', 'Guardou cinquenta versículos favoritos.', 'bookmark', 250),
  ('notas-5', 'Estudioso', 'Escreveu cinco anotações de estudo.', 'pen-line', 60),
  ('notas-25', 'Mestre de Estudo', 'Escreveu vinte e cinco anotações de estudo.', 'pen-line', 250),
  ('primeira-resposta', 'Mão Estendida', 'Respondeu pela primeira vez no fórum.', 'message-circle', 20),
  ('cinco-topicos', 'Semeador de Perguntas', 'Abriu cinco tópicos no fórum.', 'message-circle', 100),
  ('cinquenta-respostas', 'Coração Fraterno', 'Respondeu cinquenta vezes no fórum.', 'users', 400),
  ('santo-padroeiro', 'Padroeiro Escolhido', 'Escolheu um santo padroeiro para caminhar consigo.', 'heart', 30),
  ('caminho-completo', 'Caminho Integral', 'Orou, leu a Escritura, favoritou e anotou — tudo isso.', 'award', 300)
ON CONFLICT (slug) DO NOTHING;